# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
sudo: required

language: python
python: 3.6

env:
  - TOXENV=py36,py27,py26

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - pip install -U tox
  - pip install python-coveralls coveralls

# command to run tests, e.g. python setup.py test
script: 
  - tox -e ${TOXENV}
  - coverage run --source=gfe_client -m unittest -v
  - coverage report -m

after_success:
  - coveralls


